<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js"></script>
<script src="js/angular-file-upload.js"></script>
<script src="js/excanvas.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<!-- <script src="js/bootstrap.js"></script> -->
<script src="js/base.js"></script>
<script src="js/jquery-cookies.min.js"></script>
<script src="js/SessaoCtrl.js?v20140819"></script>
<%-- <script src="js/angular-date-fix.js"></script> --%>
<script src="js/moment.min.js"></script>
<script src="js/moment-timezone-with-data.min.js"></script>
<script src="js/angular-datepicker.min.js"></script>
