package org.csi.controle.core.entidade;

public enum ChaveConfiguracao {

	RAIZ_FOTOS, TEMPO_SESSAO, CAMINHO_BASE, PROPORCAO_THUMB, LINK_CLIENTE, PERCENTO_PROTOCOLO, 
	CORREIOS_USUARIO, CORREIOS_SENHA, CORREIOS_WSDL, JADLOG_USUARIO, JADLOG_SENHA, JADLOG_WSDL, 
	DHL_USUARIO, DHL_SENHA, DHL_WSDL;
	
}
